# Generated by Django 4.1.4 on 2022-12-16 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(default=True, max_length=50, null=True)),
                ('short_intro', models.TextField(default=True, null=True)),
                ('email', models.CharField(default=True, max_length=50, null=True)),
                ('insta_id', models.CharField(default=True, max_length=50, null=True)),
                ('location', models.CharField(default=True, max_length=50, null=True)),
                ('github_link', models.CharField(default=True, max_length=100, null=True)),
                ('twitter_acc', models.CharField(default=True, max_length=50, null=True)),
                ('youtube_acc', models.CharField(default=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
