# Generated by Django 4.1.4 on 2022-12-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_profile_pic_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
