# Generated by Django 4.1.4 on 2022-12-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_id_alter_skill_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
