# Generated by Django 4.1.4 on 2022-12-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unread_msgs',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
