# Generated by Django 4.1.4 on 2023-01-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_message_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['unread_msgs', '-created']},
        ),
    ]
