# Generated by Django 4.1.4 on 2023-01-28 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_options_alter_message_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 18, 55, 20, 583012)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 18, 55, 20, 583012)),
        ),
        migrations.AlterField(
            model_name='skills',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 18, 55, 20, 583012)),
        ),
    ]
