# Generated by Django 4.1.4 on 2023-01-29 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_message_created_alter_profile_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 23, 26, 35, 11679)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 23, 26, 34, 996055)),
        ),
        migrations.AlterField(
            model_name='skills',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 23, 26, 35, 11679)),
        ),
    ]
