# Generated by Django 4.1.4 on 2023-01-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vedio',
            field=models.FileField(blank=True, null=True, upload_to='images/vedio'),
        ),
    ]
