# Generated by Django 4.1.4 on 2023-01-29 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_created_alter_review_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_image',
            new_name='Anime_image',
        ),
        migrations.AddField(
            model_name='project',
            name='filler_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 23, 26, 35, 11679)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 23, 26, 35, 11679)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 23, 26, 35, 11679)),
        ),
    ]
