# Generated by Django 4.1.4 on 2023-01-29 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_rename_filler_link_project_filler_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='filler_links',
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 23, 31, 23, 989714)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 23, 31, 23, 989714)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 23, 31, 23, 989714)),
        ),
    ]
